name: Local Test Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Tokyo'
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Test setup, run and check coverage
        if: always()
        shell: bash
        run: |
          python3 --version
          python3 -m pip install --upgrade pip
          python3 -m pip install "poetry>=1.7.0"
          poetry install

          # テスト実行とカバレッジレポート
          poetry run task test_ci_xml

          # poetryの環境内でcoverageを実行
          poetry run coverage report
          coverage_percentage=$(poetry run coverage report | grep TOTAL | awk '{print $NF}' | sed 's/%//')
          echo "Current coverage: ${coverage_percentage}%"
